name: Build and Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  dev:
    deploy_app:
      uses: ./.github/workflows/reusableWorkflow.yml@deploy_app
      name: run the job
      secrets: inherit
      with:
        environment: "dev"
