name: Build and Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  dev:
    uses: ./.github/workflows/reusable.yml
    name: run the job
    secrets: inherit
    with:
        environment: "dev"
