name: Build and Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  dev:
    deploy_app:
      name: run the job
      uses: ./.github/workflows/reusableWorkflow.yml
      with:
        environment: "dev"
