name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  main:
    uses: ./.github/workflows/reusable.yml
    name: run the job
    secrets: inherit
    with:
      environment: "main"
