name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  VITE_TEST: ${{ vars.VITE_TEST }}
jobs:
  deploy_app:
    name: Deploy App
    environment: ${{ inputs.environment}}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Copy and rename file
        shell: cmd
        run: |
          copy ".npmrc.example" ".npmrc"

      - name: Replace secret
        run: |
          node -e "
            const fs = require('fs');
            const content = fs.readFileSync('.npmrc', 'utf8');
            const updated = content.replace(/NPMRC/g, '${{ secrets.NPMRC }}');
            fs.writeFileSync('.npmrc', updated);
          "

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to IIS
        shell: cmd
        run: |
          iisreset /stop
          xcopy /s /y .\dist c:\test
          iisreset /start